--  경기도에 위치한 창고
-- 냉동시설 여부가 NULL인 경우, 'N'으로 출력
SELECT 
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    CASE WHEN FREEZER_YN IS NULL THEN 'N' ELSE FREEZER_YN END AS FREEZER_YN
From FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
order by WAREHOUSE_ID
