-- 더 이상 업그레이드할 수 없는 아이템 
-- PARENT ID에 없는 아이디 


SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t ON i.ITEM_ID = t.ITEM_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE t2
    WHERE t2.PARENT_ITEM_ID = t.ITEM_ID
)
ORDER BY i.ITEM_ID DESC;

