-- 음식종류별로 즐겨찾기수가 가장 많은 식당
-- 음식 종류를 기준으로 내림차순 정렬

WITH F AS(
    SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, ri.FAVORITES
FROM REST_INFO ri
JOIN F f ON F.FOOD_TYPE=ri.FOOD_TYPE and ri.FAVORITES=f.FAVORITES
ORDER BY FOOD_TYPE desc
